db_params:

  adapter:  sqlite3
  database: /home/jim/src/comfy_site/db/development.sqlite3
  pool:     5
  timeout:  5000


website_directory: ./test/bpd


for_each_page:

  create_new:
    - page
    - block

  dump_content_into:
    - page.content
    - block.content

  link_these_fields:
    block.page_id: page.id

  fill_these_fields_with:
    page:
      site_id:        1
      layout_id:      1
      parent_id:      1
      label:          $title
      slug:           $filename.sub(/\.[a-z]+$/, '')
      full_path:      /$filename.sub(/\.[a-z]+$/, '')
      position:       0
      children_count: 0
      is_published:   true
      is_shared:      false
    block:
      identifier: content
