title_selector:            at_css('title').text if at_css('title')
meta_description_selector: at_css('meta[name="DESCRIPTION"]')['content'] if at_css('meta[name="DESCRIPTION"]')
content_selector:          at_css('table[width="622"]')

element_selectors:
  - css('p').to_html
  - css('img').to_html


encode_html_as:            Windows-1252
condense_spaces:           true

characters_to_strip:
  - \n

for_each_element:
  p(class=lg-subhead):
    convert_to:            h1

  p:
    remove_if_empty:       true
    remove_children:
      - img

  h1:
    remove_attributes:
      - class

  img:
    surround_with:         <br />
    src:                   File.basename('$src')
